--- 
title: Slingshot Developer Blog
root: 
permalink: pretty
authors: 
- id: jstotz
  name: Jay Stotz
  uri: http://github.com/jstotz
- id: mcameron
  name: Myke Cameron
  uri: http://github.com/mykecameron