#!/usr/bin/env ruby

require 'optparse'

def slugify(str)
	accents = { 
	  ['á','à','â','ä','ã'] => 'a',
	  ['Ã','Ä','Â','À'] => 'A',
	  ['é','è','ê','ë'] => 'e',
	  ['Ë','É','È','Ê'] => 'E',
	  ['í','ì','î','ï'] => 'i',
	  ['Î','Ì'] => 'I',
	  ['ó','ò','ô','ö','õ'] => 'o',
	  ['Õ','Ö','Ô','Ò','Ó'] => 'O',
	  ['ú','ù','û','ü'] => 'u',
	  ['Ú','Û','Ù','Ü'] => 'U',
	  ['ç'] => 'c', ['Ç'] => 'C',
	  ['ñ'] => 'n', ['Ñ'] => 'N'
	}
	
	accents.each do |ac,rep|
	  ac.each do |s|
		  str.gsub!(s, rep)
	  end
	end
	
	str = str.gsub(/[^a-zA-Z0-9 ]/,"")
	str.gsub!(/[ ]+/,' ')
	str.gsub!(' ','-')
	str.downcase
end

if !ARGV[0]
  puts "Must specify a title as the first argument"
  exit(1)
end

author = `whoami`.strip
post_date = Time.now.strftime('%Y-%m-%d')
title = ARGV[0]
slug = slugify(title)
format = 'markdown'
filename = File.join('_posts', "#{post_date}-#{slug}.#{format}")

content = <<-CONTENT
---
title: #{title}
author: #{author}
layout: default
---

CONTENT

puts "Creating new blog post:\n\n  Author:  #{author}\n    File:  #{filename}"

if File.exists?(filename)
  puts "\nERROR: File already exists. Aborting."
  exit(1)
end

File.open(filename, 'w') {|f| f.write(content)}
system("$EDITOR #{filename}")